# Generated by Django 2.2.28 on 2022-05-03 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='status',
            field=models.CharField(choices=[('r', 'Reviewed'), ('e', 'Error'), ('n', 'Not reviewed'), ('a', 'Accepted')], default='n', max_length=1),
            preserve_default=False,
        ),
    ]
