# Generated by Django 2.2.28 on 2022-05-03 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220503_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='owner',
        ),
    ]
