# Generated by Django 2.2.28 on 2022-05-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_website_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
