# Generated by Django 2.2.28 on 2022-05-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='car_name',
            field=models.ManyToManyField(to='users.Car', verbose_name="the user's cars"),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=50, verbose_name='chosen user_name'),
        ),
    ]
